### ISSUE TITLE
429 status code response when using leaflet map with zoom >= 10 

### ISSUE THREAD

**Issue by vasiledraghita** [kartotherian/kartotherian#121]
![Screen Shot 2020-02-05 at 14 42 53](https://user-images.githubusercontent.com/24325243/73842774-e8815000-4825-11ea-902c-54a02cb79f1a.jpg)

**Comment by aidzas** [comment]
Same problem

**Comment by vitale232** [comment]
I've started to see something similar in my application, too. I'm using OpenLayers in lieu of Leaflet, for what that's worth. The issue seems to be worse at zooms >= 10, but I see it in lesser zoom levels, too.

Let me know if I can help debug at all. Thanks!
![image (2)](https://user-images.githubusercontent.com/8504254/73972230-6dd03780-48ee-11ea-90b7-436b9cb5f609.png)

**Comment by nkarampi** [comment]
We are also experiencing the same issue.

Please share an update, as we need to be aware whether the project is still active or not.

**Comment by Toommi** [comment]
+1

**Comment by thomasFoglia** [comment]
Same issue.. any solution ? thanks

**Comment by hartman** [comment]
You are using the Wikimedia Maps services, which while it runs karthotherian, makes this question not really related to this repo.

Due to [excessive 3rd party use](https://wikitech.wikimedia.org/wiki/Incident_documentation/20200204-maps), the Wikimedia Foundation was required to aggressively throttle 3rd party use and will only serve 3rd parties tiles that are currently in the WMF Varnish cache layer, to make sure basic service can remain available to Wikimedia itself. https://phabricator.wikimedia.org/T245145#5880898.

Regarding the future, I quote:
> If you are a non-Wikimedia user of our maps service, I would begin making contingency plans for another tile provider and expect that the current "cached only" tiles limitation will remain in place going forward.

Relevant mailing list threads:
https://lists.wikimedia.org/pipermail/maps-l/2020-February/001707.html
https://lists.wikimedia.org/pipermail/maps-l/2020-March/001709.html
